#!/usr/bin/env python3
"""
BitNet ONNX converter for ternarycore.

Two modes:
  1. Real ONNX:  python convert_bitnet_onnx.py model.onnx
  2. Synthetic:   python convert_bitnet_onnx.py --synthetic --rows 4 --cols 4

In either mode, generates:
  - Verilog testbench stimulus for the pipeline RTL
  - Expected output file for verification
  - C++ stimulus header for Verilator tests
"""

import argparse
import json
import struct
import sys
from pathlib import Path

# ── Ternary encoding ──────────────────────────────────────────────
# BitNet b1.58 weight encoding (2 bits per weight):
#   00 = 0 (zero)
#   01 = +1 (positive)
#   10 = -1 (negative)
#   11 = invalid

def pack_ternary_weights(weights: list[int], cols: int) -> int:
    """Pack list of ternary values into 2*cols-bit weight_enc word."""
    packed = 0
    for i, w in enumerate(weights[:cols]):
        enc = {0: 0, 1: 1, -1: 2}.get(w, 0)
        packed |= enc << (2 * i)
    return packed


# ── Test vector generation ─────────────────────────────────────────

def generate_tests(rows: int, cols: int, rng_seed: int = 42):
    """Generate synthetic BitNet test vectors.

    Yields dicts with:
      activation: int8 raw activation value
      inv:        int inverse absmax (precomputed)
      weights:    [weight_per_col] ternary values
      alpha:      [alpha_per_col] scale values (Q15)
      activations_per_row: list of int8 activations (all rows)
    """
    import random
    rng = random.Random(rng_seed)

    test_vectors = []

    for row in range(rows):
        activations = [rng.randint(-50, 50) for _ in range(cols)]
        weights_per_col = [rng.choice([-1, 0, 1]) for _ in range(cols)]
        alphas = [rng.randint(1, 65535) for _ in range(cols)]

        # Compute absmax for this row
        absmax = max(abs(a) for a in activations) or 1
        inv = round(32768 * 127 / absmax)

        # Compute expected output (software reference)
        expected = []
        for c in range(cols):
            dot = sum(a * weights_per_col[c] for a in activations)
            scaled = dot * alphas[c] // 32768  # Q15
            expected.append(scaled)

        test_vectors.append({
            "activations": activations,
            "weights": weights_per_col,
            "alphas": alphas,
            "inv": inv,
            "absmax": absmax,
            "expected": expected,
        })

    return test_vectors


# ── Verilog output ─────────────────────────────────────────────────

def write_verilog_tb(tests, path: Path):
    """Write a Verilog testbench that drives the pipeline."""
    lines = [
        "// Auto-generated by convert_bitnet_onnx.py",
        "`timescale 1ns / 1ps",
        "module tb_bitnet_pipeline;",
        "    reg clk, rst_n;",
        f"    reg [7:0] activation;",
        f"    reg [21:0] inv;",
        f"    reg [63:0] alpha;",
        f"    reg [7:0] weight_enc;",
        f"    wire [127:0] result;",
        f"    wire valid_out;",
        "",
        f"    ternary_pipeline #(.VECTOR_LEN({len(tests[0]['activations'])})) dut(",
        "        .clk(clk), .rst_n(rst_n),",
        "        .valid_in(1'b1), .activation(activation), .inv(inv),",
        "        .alpha(alpha), .weight_enc(weight_enc),",
        "        .result(result), .valid_out(valid_out)",
        "    );",
        "",
        "    always #5 clk = ~clk;",
        "",
    ]

    # Stimulus
    lines.append("    initial begin")
    lines.append("        $dumpfile(\"tb_bitnet_pipeline.vcd\");")
    lines.append("        $dumpvars(0, tb_bitnet_pipeline);")
    lines.append("        clk = 0; rst_n = 0;")
    lines.append("        #10 rst_n = 1;")

    for test in tests:
        inv_val = test["inv"]
        w_packed = pack_ternary_weights(test["weights"], len(test["weights"]))
        alpha_packed = sum(
            a << (16 * c) for c, a in enumerate(test["alphas"])
        )

        for act in test["activations"]:
            lines.append(f"        activation = {act}; inv = {inv_val}; "
                         f"weight_enc = {w_packed}; alpha = {alpha_packed}; #10;")

        # Wait for pipeline to drain
        lines.append("        @(posedge valid_out);")
        lines.append("        // result = ${:x} expected = {:x}".format(
            0,  # placeholder
            0,  # placeholder
        ))

    lines.append("        #20 $finish;")
    lines.append("    end")
    lines.append("endmodule")

    path.write_text("\n".join(lines) + "\n")


# ── CLI ────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Convert BitNet ONNX model to ternarycore test vectors"
    )
    parser.add_argument("model", nargs="?", help="Path to .onnx file")
    parser.add_argument("--synthetic", action="store_true",
                        help="Generate synthetic test data")
    parser.add_argument("--rows", type=int, default=4, help="Rows to generate")
    parser.add_argument("--cols", type=int, default=4,
                        help="Columns (dot units)")
    parser.add_argument("--output-dir", "-o", type=Path, default=Path("."),
                        help="Output directory")
    args = parser.parse_args()

    if args.synthetic or not args.model:
        print(f"Generating {args.rows}×{args.cols} synthetic test vectors...")
        tests = generate_tests(args.rows, args.cols)

        # Write Verilog testbench
        tb_path = args.output_dir / "tb_bitnet_pipeline.v"
        write_verilog_tb(tests, tb_path)
        print(f"  Verilog testbench: {tb_path}")

        # Write expected outputs as JSON
        json_path = args.output_dir / "expected_outputs.json"
        json_path.write_text(json.dumps(tests, indent=2, default=str))
        print(f"  Expected outputs:  {json_path}")

        print(f"  {len(tests)} test rows generated.")
        print()
        print("To verify: cd sim && iverilog -g2012 -o tb_bitnet_pipeline \\")
        print(f"  ../rtl/*.v ../tools/{tb_path.name} && vvp tb_bitnet_pipeline")
        return

    # Real ONNX model support (future)
    if args.model:
        print(f"Loading ONNX model: {args.model}")
        try:
            import onnx
            model = onnx.load(args.model)
            onnx.checker.check_model(model)
            print(f"  Model loaded: {model.graph.name}")
            print(f"  {len(model.graph.node)} nodes")
            print()
            print("ONNX parsing for BitNet weights not yet implemented.")
            print("Use --synthetic for now, or contribute the ONNX parser.")
        except Exception as e:
            print(f"Error loading model: {e}", file=sys.stderr)
            sys.exit(1)


if __name__ == "__main__":
    main()